### PR TITLE
zstdless: add shebang and quote $@

### LINKED ISSUE #496: zstdless has no shebang line
The new `zstdless` command is implemented as a script but it has no shebang line at the top.

```
[/tmp/test-zstd/bin]
$ cat zstdless
zstdcat $@ | less
```

This could lead to varying behavior or breakage, depending on what system and shell it's being run under. For example, under `fish` it won't run at all.

```
janke@angharad /p/t/t/bin> ./zstdless foo
Failed to execute process './zstdless'. Reason:
exec: Exec format error
The file './zstdless' is marked as an executable but could not be run by the operating system.
```

It seems like this should have a `#!/bin/sh` shebang line, since that's a shell it's known to work with.

I think that `$@` should also have double-quotes around it, in case the arguments have spaces in them.

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #496.

Adds a shebang line to `zstdless` so it works under more environments.

Quotes the `$@` variable to protect against spaces etc in the input filenames.

### CODE REVIEW

**Comment by apjanke** [comment]
Closing this because I didn't get the branch setup right.

**Comment by apjanke** [comment]
Okay, I think the branch setup is right after all (merging to `dev`), and I've signed the individual CLA. Reopening.

**Comment by apjanke** [comment]
The CI tests on this failed with a build error in a file this PR didn't change.

```
make[1]: Leaving directory `/home/travis/build/facebook/zstd/lib'
gcc-4.8 -I../lib -I../lib/common -I../lib/dictBuilder -I../lib/deprecated -I../programs -O3 -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef   symbols.c -o symbols -Wl,-rpath=../lib ../lib/libzstd.so
symbols.c:131:3: warning: ‘ZDICT_addEntropyTablesFromBuffer’ is deprecated (declared at ../lib/dictBuilder/zdict.h:139): use ZDICT_finalizeDictionary() instead [-Wdeprecated-declarations]
   &ZDICT_addEntropyTablesFromBuffer,
   ^
/tmp/cc8YPreK.o:(.data+0x380): undefined reference to `ZDICT_addEntropyTablesFromBuffer'
collect2: error: ld returned 1 exit status
make: *** [symbols] Error 1
make: Leaving directory `/home/travis/build/facebook/zstd/tests'
The command "sh -c "$Cmd"" exited with 2.
```

I think that's due to the deprecation warning fixed by #498.

**Comment by terrelln** [comment]
Yeah, thats the same failure fixed by #498.

**Comment by Cyan4973** [comment]
Thanks, looks all good @apjanke !
Don't worry about the test failure, it has been fixed by @terrelln in another PR
