### ISSUE TITLE
Wrong assert/Typo in zstd_decompress.c

### ISSUE THREAD

**Issue by Neumann-A** [facebook/zstd#2386]
**Describe the bug**
https://github.com/facebook/zstd/blob/f54109c5894952b2c9f0ee816d8a1f45116b5ce1/lib/decompress/zstd_decompress.c#L735
should probably not be `<=-` but `<=` instead.
Disccovered in vcpkg after upgrading zstd to 1.4.5 due to error:
```
       (ClCompile Ziel) -> 
         E:\vcpkg_folders\qt6_2\buildtrees\zstd\src\7a785666b6-0009a14924\lib\decompress\zstd_decompress.c(724,13): error C4146: unary minus operator applied to unsigned type, result still unsigned [E:\vcpkg_folders\qt6_2\buildtrees\zstd\x64-uwp-dbg\lib\libzstd_shared.vcxproj]
```
(Don't mind the difference in Line number. It is probably due to the different of tag 1.4.5 vs HEAD)

**Expected behavior**
Code compiles

**Related**
https://github.com/microsoft/vcpkg/pull/14395
